name: Open Authenticator component
on: [push, pull_request]

jobs:
  build-test:
    name: Test Build of component
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:release-v4.1
    strategy:
      matrix:
        test-apps: [reading-battery-percentage, reading-switches, using-load-switch]
    steps:  
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.test-apps }}
        run: |
          . $IDF_PATH/export.sh
          cd examples/
          cd ${{ matrix.test-apps }}
          idf.py build
